/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AAddExpr6 extends PExpr6
{
    private PExpr6 _expr6_;
    private TPlusOp _plusOp_;
    private PExpr7 _expr7_;

    public AAddExpr6()
    {
        // Constructor
    }

    public AAddExpr6(
        @SuppressWarnings("hiding") PExpr6 _expr6_,
        @SuppressWarnings("hiding") TPlusOp _plusOp_,
        @SuppressWarnings("hiding") PExpr7 _expr7_)
    {
        // Constructor
        setExpr6(_expr6_);

        setPlusOp(_plusOp_);

        setExpr7(_expr7_);

    }

    @Override
    public Object clone()
    {
        return new AAddExpr6(
            cloneNode(this._expr6_),
            cloneNode(this._plusOp_),
            cloneNode(this._expr7_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddExpr6(this);
    }

    public PExpr6 getExpr6()
    {
        return this._expr6_;
    }

    public void setExpr6(PExpr6 node)
    {
        if(this._expr6_ != null)
        {
            this._expr6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr6_ = node;
    }

    public TPlusOp getPlusOp()
    {
        return this._plusOp_;
    }

    public void setPlusOp(TPlusOp node)
    {
        if(this._plusOp_ != null)
        {
            this._plusOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plusOp_ = node;
    }

    public PExpr7 getExpr7()
    {
        return this._expr7_;
    }

    public void setExpr7(PExpr7 node)
    {
        if(this._expr7_ != null)
        {
            this._expr7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr6_)
            + toString(this._plusOp_)
            + toString(this._expr7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr6_ == child)
        {
            this._expr6_ = null;
            return;
        }

        if(this._plusOp_ == child)
        {
            this._plusOp_ = null;
            return;
        }

        if(this._expr7_ == child)
        {
            this._expr7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr6_ == oldChild)
        {
            setExpr6((PExpr6) newChild);
            return;
        }

        if(this._plusOp_ == oldChild)
        {
            setPlusOp((TPlusOp) newChild);
            return;
        }

        if(this._expr7_ == oldChild)
        {
            setExpr7((PExpr7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
