/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AArrayAExpr extends PAExpr
{
    private TId _id_;
    private final LinkedList<PAExpr> _aExpr_ = new LinkedList<PAExpr>();

    public AArrayAExpr()
    {
        // Constructor
    }

    public AArrayAExpr(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PAExpr> _aExpr_)
    {
        // Constructor
        setId(_id_);

        setAExpr(_aExpr_);

    }

    @Override
    public Object clone()
    {
        return new AArrayAExpr(
            cloneNode(this._id_),
            cloneList(this._aExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArrayAExpr(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAExpr> getAExpr()
    {
        return this._aExpr_;
    }

    public void setAExpr(List<PAExpr> list)
    {
        this._aExpr_.clear();
        this._aExpr_.addAll(list);
        for(PAExpr e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aExpr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PAExpr> i = this._aExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
