/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AAssignmentStmt extends PAssignmentStmt
{
    private TId _id_;
    private final LinkedList<PAssignmentStmt2> _assignmentStmt2_ = new LinkedList<PAssignmentStmt2>();
    private TAsignOp _asignOp_;
    private PExpression _expression_;

    public AAssignmentStmt()
    {
        // Constructor
    }

    public AAssignmentStmt(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<PAssignmentStmt2> _assignmentStmt2_,
        @SuppressWarnings("hiding") TAsignOp _asignOp_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setId(_id_);

        setAssignmentStmt2(_assignmentStmt2_);

        setAsignOp(_asignOp_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AAssignmentStmt(
            cloneNode(this._id_),
            cloneList(this._assignmentStmt2_),
            cloneNode(this._asignOp_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAssignmentStmt(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAssignmentStmt2> getAssignmentStmt2()
    {
        return this._assignmentStmt2_;
    }

    public void setAssignmentStmt2(List<PAssignmentStmt2> list)
    {
        this._assignmentStmt2_.clear();
        this._assignmentStmt2_.addAll(list);
        for(PAssignmentStmt2 e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TAsignOp getAsignOp()
    {
        return this._asignOp_;
    }

    public void setAsignOp(TAsignOp node)
    {
        if(this._asignOp_ != null)
        {
            this._asignOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._asignOp_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._assignmentStmt2_)
            + toString(this._asignOp_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._assignmentStmt2_.remove(child))
        {
            return;
        }

        if(this._asignOp_ == child)
        {
            this._asignOp_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PAssignmentStmt2> i = this._assignmentStmt2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAssignmentStmt2) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._asignOp_ == oldChild)
        {
            setAsignOp((TAsignOp) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
