/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ABinAExpr extends PAExpr
{
    private PAOp _aOp_;
    private PAExpr _e1_;
    private PAExpr _e2_;

    public ABinAExpr()
    {
        // Constructor
    }

    public ABinAExpr(
        @SuppressWarnings("hiding") PAOp _aOp_,
        @SuppressWarnings("hiding") PAExpr _e1_,
        @SuppressWarnings("hiding") PAExpr _e2_)
    {
        // Constructor
        setAOp(_aOp_);

        setE1(_e1_);

        setE2(_e2_);

    }

    @Override
    public Object clone()
    {
        return new ABinAExpr(
            cloneNode(this._aOp_),
            cloneNode(this._e1_),
            cloneNode(this._e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABinAExpr(this);
    }

    public PAOp getAOp()
    {
        return this._aOp_;
    }

    public void setAOp(PAOp node)
    {
        if(this._aOp_ != null)
        {
            this._aOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aOp_ = node;
    }

    public PAExpr getE1()
    {
        return this._e1_;
    }

    public void setE1(PAExpr node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    public PAExpr getE2()
    {
        return this._e2_;
    }

    public void setE2(PAExpr node)
    {
        if(this._e2_ != null)
        {
            this._e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aOp_)
            + toString(this._e1_)
            + toString(this._e2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aOp_ == child)
        {
            this._aOp_ = null;
            return;
        }

        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        if(this._e2_ == child)
        {
            this._e2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aOp_ == oldChild)
        {
            setAOp((PAOp) newChild);
            return;
        }

        if(this._e1_ == oldChild)
        {
            setE1((PAExpr) newChild);
            return;
        }

        if(this._e2_ == oldChild)
        {
            setE2((PAExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
