/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ACallAExpr extends PAExpr
{
    private TId _id_;
    private PAExpr _obj_;
    private final LinkedList<PAExpr> _list_ = new LinkedList<PAExpr>();

    public ACallAExpr()
    {
        // Constructor
    }

    public ACallAExpr(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAExpr _obj_,
        @SuppressWarnings("hiding") List<PAExpr> _list_)
    {
        // Constructor
        setId(_id_);

        setObj(_obj_);

        setList(_list_);

    }

    @Override
    public Object clone()
    {
        return new ACallAExpr(
            cloneNode(this._id_),
            cloneNode(this._obj_),
            cloneList(this._list_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACallAExpr(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAExpr getObj()
    {
        return this._obj_;
    }

    public void setObj(PAExpr node)
    {
        if(this._obj_ != null)
        {
            this._obj_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._obj_ = node;
    }

    public LinkedList<PAExpr> getList()
    {
        return this._list_;
    }

    public void setList(List<PAExpr> list)
    {
        this._list_.clear();
        this._list_.addAll(list);
        for(PAExpr e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._obj_)
            + toString(this._list_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._obj_ == child)
        {
            this._obj_ = null;
            return;
        }

        if(this._list_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._obj_ == oldChild)
        {
            setObj((PAExpr) newChild);
            return;
        }

        for(ListIterator<PAExpr> i = this._list_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
