/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AConcatAOp extends PAOp
{
    private TConcatOp _concatOp_;

    public AConcatAOp()
    {
        // Constructor
    }

    public AConcatAOp(
        @SuppressWarnings("hiding") TConcatOp _concatOp_)
    {
        // Constructor
        setConcatOp(_concatOp_);

    }

    @Override
    public Object clone()
    {
        return new AConcatAOp(
            cloneNode(this._concatOp_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcatAOp(this);
    }

    public TConcatOp getConcatOp()
    {
        return this._concatOp_;
    }

    public void setConcatOp(TConcatOp node)
    {
        if(this._concatOp_ != null)
        {
            this._concatOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concatOp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._concatOp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._concatOp_ == child)
        {
            this._concatOp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._concatOp_ == oldChild)
        {
            setConcatOp((TConcatOp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
