/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AEqExpr3 extends PExpr3
{
    private PExpr5 _e1_;
    private TEqOp _eqOp_;
    private PExpr5 _e2_;

    public AEqExpr3()
    {
        // Constructor
    }

    public AEqExpr3(
        @SuppressWarnings("hiding") PExpr5 _e1_,
        @SuppressWarnings("hiding") TEqOp _eqOp_,
        @SuppressWarnings("hiding") PExpr5 _e2_)
    {
        // Constructor
        setE1(_e1_);

        setEqOp(_eqOp_);

        setE2(_e2_);

    }

    @Override
    public Object clone()
    {
        return new AEqExpr3(
            cloneNode(this._e1_),
            cloneNode(this._eqOp_),
            cloneNode(this._e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEqExpr3(this);
    }

    public PExpr5 getE1()
    {
        return this._e1_;
    }

    public void setE1(PExpr5 node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    public TEqOp getEqOp()
    {
        return this._eqOp_;
    }

    public void setEqOp(TEqOp node)
    {
        if(this._eqOp_ != null)
        {
            this._eqOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._eqOp_ = node;
    }

    public PExpr5 getE2()
    {
        return this._e2_;
    }

    public void setE2(PExpr5 node)
    {
        if(this._e2_ != null)
        {
            this._e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e1_)
            + toString(this._eqOp_)
            + toString(this._e2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        if(this._eqOp_ == child)
        {
            this._eqOp_ = null;
            return;
        }

        if(this._e2_ == child)
        {
            this._e2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e1_ == oldChild)
        {
            setE1((PExpr5) newChild);
            return;
        }

        if(this._eqOp_ == oldChild)
        {
            setEqOp((TEqOp) newChild);
            return;
        }

        if(this._e2_ == oldChild)
        {
            setE2((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
