/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AExpressionList extends PExpressionList
{
    private final LinkedList<PExpressionList2> _expressionList2_ = new LinkedList<PExpressionList2>();
    private PExpression _expression_;

    public AExpressionList()
    {
        // Constructor
    }

    public AExpressionList(
        @SuppressWarnings("hiding") List<PExpressionList2> _expressionList2_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setExpressionList2(_expressionList2_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AExpressionList(
            cloneList(this._expressionList2_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpressionList(this);
    }

    public LinkedList<PExpressionList2> getExpressionList2()
    {
        return this._expressionList2_;
    }

    public void setExpressionList2(List<PExpressionList2> list)
    {
        this._expressionList2_.clear();
        this._expressionList2_.addAll(list);
        for(PExpressionList2 e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressionList2_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressionList2_.remove(child))
        {
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PExpressionList2> i = this._expressionList2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PExpressionList2) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
