/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AGtExpr3 extends PExpr3
{
    private PExpr5 _e1_;
    private TGtOp _gtOp_;
    private PExpr5 _e2_;

    public AGtExpr3()
    {
        // Constructor
    }

    public AGtExpr3(
        @SuppressWarnings("hiding") PExpr5 _e1_,
        @SuppressWarnings("hiding") TGtOp _gtOp_,
        @SuppressWarnings("hiding") PExpr5 _e2_)
    {
        // Constructor
        setE1(_e1_);

        setGtOp(_gtOp_);

        setE2(_e2_);

    }

    @Override
    public Object clone()
    {
        return new AGtExpr3(
            cloneNode(this._e1_),
            cloneNode(this._gtOp_),
            cloneNode(this._e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGtExpr3(this);
    }

    public PExpr5 getE1()
    {
        return this._e1_;
    }

    public void setE1(PExpr5 node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    public TGtOp getGtOp()
    {
        return this._gtOp_;
    }

    public void setGtOp(TGtOp node)
    {
        if(this._gtOp_ != null)
        {
            this._gtOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._gtOp_ = node;
    }

    public PExpr5 getE2()
    {
        return this._e2_;
    }

    public void setE2(PExpr5 node)
    {
        if(this._e2_ != null)
        {
            this._e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e1_)
            + toString(this._gtOp_)
            + toString(this._e2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        if(this._gtOp_ == child)
        {
            this._gtOp_ = null;
            return;
        }

        if(this._e2_ == child)
        {
            this._e2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e1_ == oldChild)
        {
            setE1((PExpr5) newChild);
            return;
        }

        if(this._gtOp_ == oldChild)
        {
            setGtOp((TGtOp) newChild);
            return;
        }

        if(this._e2_ == oldChild)
        {
            setE2((PExpr5) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
