/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ALoopAStmt extends PAStmt
{
    private TWhile _while_;
    private PAExpr _aExpr_;
    private final LinkedList<PAStmt> _aStmt_ = new LinkedList<PAStmt>();

    public ALoopAStmt()
    {
        // Constructor
    }

    public ALoopAStmt(
        @SuppressWarnings("hiding") TWhile _while_,
        @SuppressWarnings("hiding") PAExpr _aExpr_,
        @SuppressWarnings("hiding") List<PAStmt> _aStmt_)
    {
        // Constructor
        setWhile(_while_);

        setAExpr(_aExpr_);

        setAStmt(_aStmt_);

    }

    @Override
    public Object clone()
    {
        return new ALoopAStmt(
            cloneNode(this._while_),
            cloneNode(this._aExpr_),
            cloneList(this._aStmt_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALoopAStmt(this);
    }

    public TWhile getWhile()
    {
        return this._while_;
    }

    public void setWhile(TWhile node)
    {
        if(this._while_ != null)
        {
            this._while_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._while_ = node;
    }

    public PAExpr getAExpr()
    {
        return this._aExpr_;
    }

    public void setAExpr(PAExpr node)
    {
        if(this._aExpr_ != null)
        {
            this._aExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExpr_ = node;
    }

    public LinkedList<PAStmt> getAStmt()
    {
        return this._aStmt_;
    }

    public void setAStmt(List<PAStmt> list)
    {
        this._aStmt_.clear();
        this._aStmt_.addAll(list);
        for(PAStmt e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._while_)
            + toString(this._aExpr_)
            + toString(this._aStmt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._while_ == child)
        {
            this._while_ = null;
            return;
        }

        if(this._aExpr_ == child)
        {
            this._aExpr_ = null;
            return;
        }

        if(this._aStmt_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._while_ == oldChild)
        {
            setWhile((TWhile) newChild);
            return;
        }

        if(this._aExpr_ == oldChild)
        {
            setAExpr((PAExpr) newChild);
            return;
        }

        for(ListIterator<PAStmt> i = this._aStmt_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAStmt) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
