/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ANegAExpr extends PAExpr
{
    private TMinusOp _minusOp_;
    private PAExpr _aExpr_;

    public ANegAExpr()
    {
        // Constructor
    }

    public ANegAExpr(
        @SuppressWarnings("hiding") TMinusOp _minusOp_,
        @SuppressWarnings("hiding") PAExpr _aExpr_)
    {
        // Constructor
        setMinusOp(_minusOp_);

        setAExpr(_aExpr_);

    }

    @Override
    public Object clone()
    {
        return new ANegAExpr(
            cloneNode(this._minusOp_),
            cloneNode(this._aExpr_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegAExpr(this);
    }

    public TMinusOp getMinusOp()
    {
        return this._minusOp_;
    }

    public void setMinusOp(TMinusOp node)
    {
        if(this._minusOp_ != null)
        {
            this._minusOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusOp_ = node;
    }

    public PAExpr getAExpr()
    {
        return this._aExpr_;
    }

    public void setAExpr(PAExpr node)
    {
        if(this._aExpr_ != null)
        {
            this._aExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusOp_)
            + toString(this._aExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusOp_ == child)
        {
            this._minusOp_ = null;
            return;
        }

        if(this._aExpr_ == child)
        {
            this._aExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusOp_ == oldChild)
        {
            setMinusOp((TMinusOp) newChild);
            return;
        }

        if(this._aExpr_ == oldChild)
        {
            setAExpr((PAExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
