/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ANegExpr8 extends PExpr8
{
    private TMinusOp _minusOp_;
    private PExpr10 _expr10_;

    public ANegExpr8()
    {
        // Constructor
    }

    public ANegExpr8(
        @SuppressWarnings("hiding") TMinusOp _minusOp_,
        @SuppressWarnings("hiding") PExpr10 _expr10_)
    {
        // Constructor
        setMinusOp(_minusOp_);

        setExpr10(_expr10_);

    }

    @Override
    public Object clone()
    {
        return new ANegExpr8(
            cloneNode(this._minusOp_),
            cloneNode(this._expr10_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegExpr8(this);
    }

    public TMinusOp getMinusOp()
    {
        return this._minusOp_;
    }

    public void setMinusOp(TMinusOp node)
    {
        if(this._minusOp_ != null)
        {
            this._minusOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusOp_ = node;
    }

    public PExpr10 getExpr10()
    {
        return this._expr10_;
    }

    public void setExpr10(PExpr10 node)
    {
        if(this._expr10_ != null)
        {
            this._expr10_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr10_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._minusOp_)
            + toString(this._expr10_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._minusOp_ == child)
        {
            this._minusOp_ = null;
            return;
        }

        if(this._expr10_ == child)
        {
            this._expr10_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._minusOp_ == oldChild)
        {
            setMinusOp((TMinusOp) newChild);
            return;
        }

        if(this._expr10_ == oldChild)
        {
            setExpr10((PExpr10) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
