/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AOtherExpr7 extends PExpr7
{
    private PExpr8 _expr8_;

    public AOtherExpr7()
    {
        // Constructor
    }

    public AOtherExpr7(
        @SuppressWarnings("hiding") PExpr8 _expr8_)
    {
        // Constructor
        setExpr8(_expr8_);

    }

    @Override
    public Object clone()
    {
        return new AOtherExpr7(
            cloneNode(this._expr8_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtherExpr7(this);
    }

    public PExpr8 getExpr8()
    {
        return this._expr8_;
    }

    public void setExpr8(PExpr8 node)
    {
        if(this._expr8_ != null)
        {
            this._expr8_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr8_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr8_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr8_ == child)
        {
            this._expr8_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr8_ == oldChild)
        {
            setExpr8((PExpr8) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
