/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AOtherExpr6 extends PExpr6
{
    private PExpr7 _expr7_;

    public AOtherExpr6()
    {
        // Constructor
    }

    public AOtherExpr6(
        @SuppressWarnings("hiding") PExpr7 _expr7_)
    {
        // Constructor
        setExpr7(_expr7_);

    }

    @Override
    public Object clone()
    {
        return new AOtherExpr6(
            cloneNode(this._expr7_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOtherExpr6(this);
    }

    public PExpr7 getExpr7()
    {
        return this._expr7_;
    }

    public void setExpr7(PExpr7 node)
    {
        if(this._expr7_ != null)
        {
            this._expr7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr7_ == child)
        {
            this._expr7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr7_ == oldChild)
        {
            setExpr7((PExpr7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
