/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AStatementList extends PStatementList
{
    private final LinkedList<PStatementList2> _statementList2_ = new LinkedList<PStatementList2>();

    public AStatementList()
    {
        // Constructor
    }

    public AStatementList(
        @SuppressWarnings("hiding") List<PStatementList2> _statementList2_)
    {
        // Constructor
        setStatementList2(_statementList2_);

    }

    @Override
    public Object clone()
    {
        return new AStatementList(
            cloneList(this._statementList2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementList(this);
    }

    public LinkedList<PStatementList2> getStatementList2()
    {
        return this._statementList2_;
    }

    public void setStatementList2(List<PStatementList2> list)
    {
        this._statementList2_.clear();
        this._statementList2_.addAll(list);
        for(PStatementList2 e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statementList2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statementList2_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStatementList2> i = this._statementList2_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatementList2) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
