/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ASubExpr6 extends PExpr6
{
    private PExpr6 _expr6_;
    private TMinusOp _minusOp_;
    private PExpr7 _expr7_;

    public ASubExpr6()
    {
        // Constructor
    }

    public ASubExpr6(
        @SuppressWarnings("hiding") PExpr6 _expr6_,
        @SuppressWarnings("hiding") TMinusOp _minusOp_,
        @SuppressWarnings("hiding") PExpr7 _expr7_)
    {
        // Constructor
        setExpr6(_expr6_);

        setMinusOp(_minusOp_);

        setExpr7(_expr7_);

    }

    @Override
    public Object clone()
    {
        return new ASubExpr6(
            cloneNode(this._expr6_),
            cloneNode(this._minusOp_),
            cloneNode(this._expr7_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASubExpr6(this);
    }

    public PExpr6 getExpr6()
    {
        return this._expr6_;
    }

    public void setExpr6(PExpr6 node)
    {
        if(this._expr6_ != null)
        {
            this._expr6_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr6_ = node;
    }

    public TMinusOp getMinusOp()
    {
        return this._minusOp_;
    }

    public void setMinusOp(TMinusOp node)
    {
        if(this._minusOp_ != null)
        {
            this._minusOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._minusOp_ = node;
    }

    public PExpr7 getExpr7()
    {
        return this._expr7_;
    }

    public void setExpr7(PExpr7 node)
    {
        if(this._expr7_ != null)
        {
            this._expr7_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expr7_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expr6_)
            + toString(this._minusOp_)
            + toString(this._expr7_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expr6_ == child)
        {
            this._expr6_ = null;
            return;
        }

        if(this._minusOp_ == child)
        {
            this._minusOp_ = null;
            return;
        }

        if(this._expr7_ == child)
        {
            this._expr7_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expr6_ == oldChild)
        {
            setExpr6((PExpr6) newChild);
            return;
        }

        if(this._minusOp_ == oldChild)
        {
            setMinusOp((TMinusOp) newChild);
            return;
        }

        if(this._expr7_ == oldChild)
        {
            setExpr7((PExpr7) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
